# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: "just-the-docs"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "Rakefile", "README.md", "scripts/"]

baseurl: # the subpath of your site, e.g. /blog

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: CVE North Stars
description: Leveraging CVEs as North Stars in vulnerability discovery and comprehension.
url: 'https://cve-north-stars.github.io' # the base hostname & protocol for your site, e.g. http://example.com

tagline: Leveraging CVEs as North Stars in vulnerability discovery and comprehension.   # it will display as the sub-title

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'


github:
  username: clearbluejar             # change to your github username

twitter:
  username: clearbluejar            # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: clearbluejar
  #email: example@doamin.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/clearbluejar      # change to your twitter homepage
    - https://github.com/clearbluejar       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: 'yeZcjox5p1UhtqcHFYkiXFGf013zyULTn74IVNLoVbE'              # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings


# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/pexels-faik-akmd-1025469.jpg"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# To disable support for mermaid diagrams (https://mermaid-js.github.io/mermaid/),
# comment out the `mermaid` and `version` keys below
# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:  
  "Blog": "https://clearbluejar.github.io/posts/cve-north-stars/"
  "Github": "https://github.com/cve-north-stars/cve-north-stars.github.io"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  - title: "<i class='fa fa-twitter fa-fw'></i> @clearbluejar"
    url: https://twitter.com/clearbluejar
  - title: "<i class='fa fa-github fa-fw'></i> clearbluejar"
    url: https://github.com/clearbluejar

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a> <a href=\"https://www.netlify.com/\">This site is powered by Netlify.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cve-north-stars/cve-north-stars.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-VRDEVXZQBB
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)


relative_links:
  enabled:     true
  collections: false
#  exclude:
#    - directory
#    - file.md

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# kramdown:
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
#     css_class: highlight
#     # default_lang: console
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1      

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all