name: Feedback
description: Provide Feedback for CVE North Stars
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide feedback!
        Don’t be afraid to give me a low score. 
        The more people tell me this isn't good yet, the more I'm motivated to make it even better. 
        [Feedback Source](https://www.julian.com/guide/write/editing)
  - type: dropdown
    id: score
    attributes:
      label: Tutorial Score
      description: Could you score this tutorial from 1-10 on how satisfied you were after reading it?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9 
        - 10
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: General Feedback      
      value: |
            - **Logic** — What didn’t you agree with?
            - **Clarity** — What was unclear?
            - **Interest** — What bored you?
            - **Brevity** — What unnecessary things should be removed?
            - **Expansion** — What unanswered questions were you left with?
            - **Cohesion** — Was there unifying flow of ideas or argument presented?
            - **Other** - Any other suggestions?
  - type: textarea
    id: problems
    attributes:
      label: Problems and Fixes
      description: List problems and suggest ideal fixes
      placeholder: Topic X isn't presented well, you should ... 
    validations:
      required: false  
